version: '3.8'

services:
  nextjs-app:
    container_name: hello-world
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: npm run build